index:
  path: /{_locale}
  controller: App\Controller\MangaController::index
  requirements:
    _locale: en|fr|de|it|rm
download:
  path: /download/{type}/{filename}
  controller: App\Controller\MangaController::download
